In [1]:
import numpy as np

### Buat Tensor

In [2]:
T1 = np.array([23, 507, 12]), 
T2 = np.array([57, 6799, 43]),
T3 = np.array([75, 2157, 12]),
T4 = np.array([87, 2618, 84])

In [3]:
tensor = np.array([T1, T2, T3, T4])
tensor

array([(array([ 23, 507,  12]),), (array([  57, 6799,   43]),),
       (array([  75, 2157,   12]),), array([  87, 2618,   84])],
      dtype=object)

In [4]:
tensor.shape

(4,)

### Melakuakn perkalian terhadap matrix

In [9]:
A =np.array([[  23, 50, 19],
        [  7, 12, 109 ],
        [  57, 67, 98]
        ])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [10]:
B = np.array([[17],
            [22],
            [19]
            ])
B

array([[17],
       [22],
       [19]])

### Melakukan perkalain terhadpat matrix 

In [11]:
A @ B

array([[1852],
       [2454],
       [4305]])

### Melakukan Transpose, hitung determinan, dann inverse terhadap matrix dibawah

In [12]:
C = np.array([[  23, 50, 19],
            [  7, 12, 109 ],
            [  57, 67, 98]
            ])
C

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [13]:
#Transpose
C.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [14]:
#hitung determinan
np.linalg.det(C)

131344.0000000002

In [15]:
#Lakukan Transpose
np.linalg.inv(C)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])